- next.config.ts
- swcMinify 옵션 제거 (기본값으로 사용됨)
- i18n 설정 제거 (App Router에서 미들웨어 활용 방식으로 변경되었으며 이미 적절히 처리중)
- images.domains 대신 remotePatterns 사용
Fixes #22
> fix: nextjs config 파일 빌드 경고

- src/components/home/TrendingCarousel.tsx
- 시안과 맞추기 위해 opt 에서 align start 설정이 필요합니다..
- 그런데 모바일 에서 align start 적용시 화면 좌측으로 이미지가 배치되는 문제
https://github.com/user-attachments/assets/d3a965d6-3a17-4079-b792-5ad8df88bb71
- useEffect 를 사용하여 화면 사이즈별로 opt 수정 
- 모바일: center, 이외 start
(#13 #30 )
> style: 메인 페이지 Carousel 반응형 스타일링

- src/app/[lang]/page.tsx
- src/components/common/LoadingThreeDots.tsx
- src/components/home/CreatePostWindow.tsx
- src/components/home/InfiniteScroll.tsx
- 모집 게시글이 등장하는 애니메이션을 추가하였습니다.
- 리액트 쿼리를 통해 예외 상황들을 처리했습니다.
- 디바운싱 처리하여 두 번씩 데이터가 불러오던 현상을 수정했습니다.
- 로딩 ui를 추가하여 조금 더 어울리는 디자인으로 적용하였습니다. (디자이너와 협의된 내용은 아닙니다.)
- 멘토님 가설대로 `fetchNextPage({ cancelRefetch: false })`를 통해 다음 페이지를 불러올 때 옵션을 추가해봤으나 해결이 되지는 않았습니다.
- 데이터를 불러오는 것과 관련된 코드 자체의 문제라기보단 스크롤할 때 ref 요소가 뷰포트에 들어올 때 한 번, 위치가 변경될 때 또 한 번, 빠르게 두 번 감지돼서 두번 불러오는 것으로 추측되어 이 부분 디바운싱 처리했습니다. 
애니메이션 구현하기 위해 기존에는 이벤트리스너 스크롤을 사용했었는데, 모션 라이브러리를 사용하면 이벤트리스너를 붙이지 않아도 돼서 성능적으로는 조금 더 나을 것으로 추측됩니다. 구현에 있어서 조금 더 간편한 부분도 있었고요.
> refactor: 무한스크롤 개선 및 애니메이션 추가

- src/app/[lang]/detail/[id]/page.tsx
- src/app/globals.css
- src/components/Btn/OptimisticUpdateLikes.tsx
- src/components/common/RecruitPost.tsx
- 찜 버튼 하트에서 북마크로 변경
- 상세 페이지 낙관적 업데이트 컴포넌트로 변경
- 홈페이지 동행하기 버튼 제거
- 배경색 figma와 동일하게 설정
> design: 찜 버튼 디자인 변경 반영, 상세페이지 낙관적 업데이트 반영

- src/app/[lang]/chat/[id]/page.tsx
- src/app/[lang]/chat/page.tsx
- src/app/[lang]/chat/tempData.ts
- src/app/[lang]/layout.tsx
- src/components/Nav/NavBar.tsx
- src/components/chat/ChatPreview.tsx
- 채팅 ui 디자인 작업 진행했습니다.
- 아직 유저 데이터가 구체적이지 않아 각 채팅방을 눌렀을 때 누른 채팅방의 대화 목록만 보이는 로직 등은 아직 구현하지 않았습니다.
- 지금까지 페이지 배경은 무조건 화이트다를 전제로 작업 진행했었는데, 채팅 창만 전체 회색 배경이 깔려있어서 전체적인 레이아웃 구조를 조금 변경했습니다.
> design: 채팅장 ui 1차 구현

- package.json
- pnpm-lock.yaml
- src/app/api/s3/route.ts
- src/components/Editor/Tiptap.tsx
- src/components/Editor/Toolbar.tsx
- src/hooks/usePasteImageUplad.ts
- S3 버킷 생성, 권한 설정 등
- presignedurl 전용 서버 엔드포인트 (api/s3) 생성 (보일러 플레이트라 복사 붙여넣기 했습니다.)
- ctrl+v 로 이미지 붙여넣을 경우 s3 업로드 하는 커스텀 훅 작성
- 버튼 컬러 디자이너 요청 반영 
- gif 이미지 같은 경우에 이미지 주소로 입력해야 들어갑니다 (크롬 브라우저 기본 동작이 png)
https://github.com/user-attachments/assets/8d88d340-132d-4a0d-9d28-3b723c502933
html 에도 s3 주소 바탕으로 랜더링 되는 것 확인
> feat: s3 presign url 통한 이미지 업로드 기능 구현 완료

- next.config.ts
- src/app/[lang]/page.tsx
- src/components/home/TrendingCarousel.tsx
- trending carousel 컴포넌트를 home 의 page.tsx 에서 fetch 하여 서버 사이드 랜더링으로 변경
- 기존 trendingpost.ts 에서 받아오지 않도록 수정
> refactor: 홈 페이지 케러셀 부분 서버 연결

- public/data/trending.ts
- src/components/Editor/PostSetupPanel.tsx
- src/components/common/RecruitPost.tsx
- src/components/home/CreatePost.tsx
- src/components/home/InfiniteScroll.tsx
- src/components/home/filter/DateFilter.tsx
- 무한스크롤 섹션의 카드 컴포넌트들에 썸네일이 없었는데, 추가했습니다.
- 데스크탑 달력 부분에서 적용을 선택하면 달력 창이 닫히도록 추가했습니다.
- 글 작성 페이지에서 기존의 마감기한 선택 범위 제한을 없애고, 과거의 날짜를 선택할 수 없도록 추가했습니다.
> design: 작성된 글의 썸네일 부분 추가, 달력들 기능 및 선택 범위 제한 수정

- src/app/[lang]/layout.tsx
- src/components/Nav/AuthNav.tsx
- src/components/Nav/Hamburger.tsx
- src/components/Nav/NavBar.tsx
- src/hooks/useSession.ts
- src/redux/ReduxProvider.tsx
- src/redux/slices/userSlice.ts
- src/redux/store.ts
- 현재 Mocking 상태로 BFF 를 설정해 두었고, 항상 Guest 로 로그인된 상태를 반환하도록 수정 하였습니다.
- layout.tsx 에서 SSR 로 api/user/me 를 조회하여 유저가 로그인 된 상태인지 검사합니다.
- 해당 데이터를 Redux 스토어에 초기값으로 주입하였고, 로그인 상태를 불러오는 useSession 훅 작성하였습니다.
- Nav 컴포넌트에서 useSession 을 사용하여 유저가 로그인 된 상태의 UI 를 조건부 랜더링 하였습니다.
- 로그인 이후 다크모드 버튼 위치가 다시 애매해졌습니다. 
- Redux dev tools
- 데스크탑 뷰
- 모바일 뷰
> feat: 로그인 상태관리, GNB 상태

- src/components/home/InfiniteScroll.tsx
- NEXT_PUBLIC_ prefix 적옹하지 않아 무한 스크롤 컴포넌트에서 환경 변수에 접근할 수 없었습니다.
> hotfix!: env 클라이언트 로드 실패 문제 (NEXT_PUBLIC_ prefix)

- src/components/profile/ProfileEditor.tsx
- src/components/profile/ReviewEditor.tsx
- src/components/ui/dialog.tsx
- 프로필 편집 창에서 useState 기반 상태 관리에서 react-hook-form, zod를 통한 폼 관리 방식으로 전환하였습니다. 
- 로직을 생각해보니 실질적으로 회원가입 폼 검사와 거의 유사하게 동작해야하고 관리할 것이 많아져, 변경을 고려했습니다.
- 모달 창을 띄운 상태에서 스크롤이 잠기도록 했습니다.
- 모달 창을 띄웠어도 뒷 배경이 완전히 투명한 것은 디자이너 요구사항이라 의도된 것입니다.
아래 내용을 유효성 검사로 오류 메시지 추가하여 사용자에게 안내
**별명**
- 한글 완성형(ㅇ, ㅏ같은 자음 모음 단독 입력 불가), 1글자 이상
- 영문으로 입력시 2글자 이상
- 한글+영문 조합 허용
**성별**
- 필수
**생년월일**
- 필수, 날짜 형식 검사
**상태메세지**
- 선택 필드
- 제출시 현재는 alert로 폼 데이터를 볼 수 있도록 해놨습니다.
- 사진 업로드 기능은 아직 추가하지 않았습니다.
> feat: 프로필 편집 창 유효성 검사 추가

- src/app/[lang]/detail/[id]/page.tsx
- src/components/Btn/KAKAOLogin.tsx
- src/components/detail/JsonToHtml.tsx
- src/components/detail/JsonToHtmlWrapper.tsx
- src/components/detail/KakaoMapViewer.tsx
- src/components/detail/PostContent.tsx
- src/components/detail/PostLocation.tsx
- src/components/detail/RecruitFooter.tsx
- src/components/detail/TabSection.tsx
- src/components/detail/UserProfile.tsx
- src/components/home/TrendingCarousel.tsx
- src/lib/calculateDays.ts
- src/types/DetailPost.ts
- 캐러셀 부분도 무한 스크롤 포스트와 똑같이 변수명, 데이터 구조 통일했습니다.  
- 상세 페이지에 카카오 지도 추가하였습니다. 
- 팁탭 json 을 html로 랜더링하는 함수를 Next 서버에서 실행을 계속 시도해서 dinamic , suspense 로 클라이언트에서만 로드 되도록 수정했습니다.  
- SEO 에 게시글이 노출되지 않는 문제가 발생할 것 같은데 이후에 고려하면 좋을 것 같습니다.
> refactor: home detail

- src/components/common/RecruitPost.tsx
- src/components/common/userChat.tsx
- src/components/detail/RecruitFooter.tsx
- src/components/profile/MyGroupPost.tsx
- src/types/DetailPost.ts
- src/types/HomePost.ts
-  모킹 데이터를 현재 날짜기준 +- 3일 로 생성하여 날짜 로직을 점검하였습니다.
-  date와 time을 하나의 Date로 합쳤습니다.  ( 글 작성이나 필터 부분은 건드리지 않았습니다. )
-  브라우저의 new Date () 는 유저기준 KST 이고 ec2 나 보편적 서버의 new Date ()  는 UDT 입니다.
-  시간과 날짜를 분리하면 날짜가 아무리 미래 이더라도, 시간에서 이상값이 생겨 과거로 인식되는 문제가 있습니다.
-  ex) 18:00 에 + 9 시간을 하면 27:00 이 되고 앞에 날짜와 더하면 날짜와 상관없이 동행 마감이 나오는 문제가 발생했습니다.
폼 작성시에도 마감 시간과 마감 날짜를 하나로 합치는게 좋을 것 같습니다. 
- 하드코딩한 데이터와 포스트 데이터 타입 충돌이 생겨서 임시로 해결해 두었습니다.
> fix: deadline date time

- public/icon/profile/defaultProfile.svg
- src/components/profile/ProfileEditor.tsx
- 프로필 편집 창에서 프로필 이미지를 업로드하는 기능을 1차로 구현했습니다. 
- s3 프리사인 URL을 받은 후 버킷으로 직접 업로드하는 방식을 사용했습니다.
- 구성된 s3 api를 통해 프리사인 URL POST 요청은 로그 통해서 200 성공한 것 확인했습니다.
- 업로드한 이미지를 바로 불러와 유저 프로필 이미지로 적용하는 과정에서, 이미지가 제대로 받아지지 않고 있습니다.
- 이것 관련해서 이미지가 바로 받아지지는 않을거라고 중현 님께서 얼핏..? 말하셨던 것 같아서 일단 이렇게 두고 코어타임때 자세히 말씀드리겠습니다.
> feat: 프로필 이미지 업로드 기능 1차 구현 (보완 필요)

- src/app/globals.css
- src/components/home/CreatePostWindow.tsx
- 현재 [#666666] 형식으로 컬러를 적용하고 있는 부분이 다크모드에서 변하도록 강제로 지정했습니다.
- 가장 좋은 방법은 컬러코드를 직접 기입한 부분을 다 유틸클래스로 전환하는 것이겠지만.. 조금 하다가 시간이 생각보다 오래걸리기도 하고 일일히 하다보니 중간에 놓치는 부분도 많이 생겨서 `global.css`를 수정하여 전역적으로 적용되게 임시조치해놨습니다.
> chore: 다크모드시 강제 색상 변경

- src/components/Btn/AssignComment.tsx
- src/components/comment/CommentBundle.tsx
- src/components/comment/SingleComment.tsx
- src/components/detail/PostInput.tsx
- API 스펙에 맞춰 댓글, 답글 분기했습니다.
- 로그인 여부에 따라 placeholder, blur, modal 등 기능 추가했습니다.
- UI 피그마에 맞춰 수정했습니다. 
- 댓글 더보기 페이지네이션 기능은 아직 구현하지 못했습니다. 생각보다 댓글 답글 작성하는 부분 시간이 오래 걸린 것 같아요. 
- 리뷰의 경우 답글이 없어서 댓글보다 난이도가 쉬울 듯 합니다. 가능하면 오늘 내로 마무리 하겠습니다.
- 이후 더보기 기능 구현할 생각 입니다.  더보기 클릭 전에 데이터가 변경되면 정합성 이슈가 있을 것 같아서 해결책을 생각해 보겠습니다. ex) 1페이지와 2페이지 데이터 중복(신규 댓글/답글 추가) or 누락(삭제)
- 댓글이나 리뷰의 개수가 많지는 않을 것 같은데 전체 페이지를 끝까지 한번에 불러오고 숨겼다가 더보기로 펼치는 방식은 어떻게 생각하시나요?
https://github.com/user-attachments/assets/890fc6f2-4d1c-4be4-b2f8-fb65fdfbba7d
> feat: 댓글 답글 (Read, Create) 완료

- src/app/[lang]/detail/[id]/page.tsx
- src/components/comment/FetchMoreComments.tsx
- src/components/comment/PostComment.tsx
- src/components/detail/TabSection.tsx
- src/lib/fetcher/fetchComments.ts
- 최초 SSR 데이터는 유지해두고, 더보기 버튼 클릭시 5 개씩 댓글을 불러오도록 수정했습니다.
- 마지막 페이지에 도달하면 접기 버튼으로 바뀌고, 접을 경우 데이터는 유지하고, 다시 전체 댓글을 펼칠 수 있게 했습니다. ( 사용자가 또 페이지네이션 수행하는 것을 방지 )
- 댓글 작성시에 router.refresh() 가 있어서 리액트 쿼리는 사용하지 않았습니다. ( 캐싱 의미가 없다고 판단했습니다. )
https://github.com/user-attachments/assets/861527d5-c5ec-436b-841d-f5e59fdc4c36
> feat: 댓글 페이징 구현 완료

- src/app/api/filter/route.ts
- src/components/profile/MypageProfile.tsx
- 소감 (Review) 에서 마이페이지의 프로필에 rating 표시 api 필드 추가 요청드렸고, 연결 완료 되었습니다.
- 남에게 보여지는 프로필 페이지의 경우에 api 수정이 필요해서 요청드린 상황 입니다.
- detail 페이지의 주최자 평점 필드도 추가 요청 드렸고, 저녁쯤 수정 가능하다고 하셔서 반영 예정입니다.
> feat: 프로필 유저 레이팅, 평점 반영

- src/components/common/RecruitPost.tsx
- src/components/detail/MemberSection.tsx
- src/components/detail/TabSection.tsx
- src/components/detail/UserProfile.tsx
- 상세페이지에서 현재 참여가 확정된 인원(작성자 포함)을 보여주는 기능을 추가했습니다.
- 참여 확정 인원을 불러오는 api에는 페이지네이션이 없어 일단 5개까지만 보이도록 반복문에 slice로 제한을 두었습니다.
- 항상 소수 첫 번째 자리까지 보이도록 했는데, 0점일때는 0.0이 좀 이상해서 0.0일때만 0으로 표기하게 했습니다.
- 상태메세지가 너무 길면 `...`으로 표기되도록 제한하였습니다.
> design: 상세페이지 참여 인원보기 추가

- src/api/gatheringApi.ts
- src/app/[lang]/chat/[kakaoId]/page.tsx
- src/app/[lang]/liked/page.tsx
- src/components/Editor/PostSetupPanel.tsx
- src/components/chat/ChatPreview.tsx
- src/components/home/FilterSelector.tsx
- src/components/home/InfiniteScroll.tsx
- src/components/home/filter/GroupThemeFilter.tsx
1. 위치검색(지도에 등록된 상호명으로 검색해야 함)
2. 선호 성별 및 나이
3. 모집 기간
4. 모임 유형
위 4가지 필터링 기능 구현 (모집 중인 동행만 보기 / n인 동행 두 가지 동작 오류)
- 받은 채팅 메세지 미리보기에서 시간 추가
- 무한스크롤 쪽 버그 수정(같은 게시글이 두 번 받아지는 현상, 같은 컴포넌트를 사용하는 찜한 동행 페이지도 마찬가지)
- 무한스크롤 쪽에서 검색과 필터링 관련 코드가 함께 작성되면서 컨플릭이 발생했습니다. 
- 우선은 나름대로 합쳐보고 로컬에서 테스트하려는 중에, 서버가 터진듯하여 로컬에서도 테스트가 불가하여 일단 두었고 이 내용 알리기 위해 PR로 남겨둡니다. 기능 작동 확인하기 전까지 merge하지 않겠습니다.
- 서버 이슈로 동작테스트를 못 한 상태라서 이 부분 브랜치 pull 받고 테스트를 해봐야 main 반영 가능해보입니다.
- 백엔드쪽에서 보내주신 필터링이 된다고하는 부분에서, 마감일이 지난 동행인지는 없는 것 같았고(종료일은 모집 마감일), 체크박스를 눌렀을 때 쿼리파라미터를 전송하는 코드는 짜놨지만 실제로 동작하지 않았습니다.
- 동행 인원인 2인, 10인 이하, ... 를 통해 필터링하는 부분 역시 일단 코드는 짜고 쿼리파라미터로 전달되는 것은 확인했으나 작동하지 않습니다. 이 부분은 아래 이미지에서 '인원 수'로 기입이 되어있어서 백엔드 쪽에서 기능은 만든 것으로 보입니다.
- 현재 기준을 2인, 10인 이상/이하로 해놔서 조금 수정도 필요할 것 같아요. 백엔드쪽 명세서에는 특정 인원 이상으로 필터링하는 것 같은데 10인 미만/10인 이상으로 …
> feat: 필터링 기능 추가, 로고쪽 검색 기능과 컨플릭 해결, 채팅 메세지 시간 표시
