- src/app/[lang]/test/page.tsx
- src/components/home/SortDateSelect.tsx
- ESLint에서 발생하는 경고에 대해 임시 주석 처리 적용
- Next.js dynamic routes에서 params가 Promise임을 반영하여 await 사용 및 props 타입 정의
> fix: ESLint warnings and fix params promise

- src/stories/Button.tsx
- src/stories/Header.tsx
- src/stories/Page.tsx
프로덕션 빌드에 포함되지 않지만 
eslint가 storybook 코드도 검사하여 에러가 있었습니다.
> hotfix: 스토리북 관련 코드 eslint 빌드에러

- src/app/[lang]/page.tsx
- src/components/home/CreatePostWindow.tsx
- 스크롤을 내리면 글 작성 버튼이 사라지고, 스크롤을 올릴 때 다시 등장하는 글 작성 버튼을 fixed로 구현했습니다.
- 애니메이션이나 화면에 보이는 조건 두 가지는 디자이너와 상의 없이 임의로 구현한 내용입니다.
~~빌드 시에 `./src/stories` 안의 컴포넌트들에서 경고가 뜨는데, 스토리북 추가와 관련된 문제 같습니다. 이 부분 확인 부탁드립니다~~
핫픽스로 고치신 것 확인했습니다!
> design: '동행 모집하기' 글 작성 버튼 추가 

- src/components/home/FilterSelector.tsx
- src/components/home/ReponsiveCalender.tsx
- src/components/ui/button.tsx
- src/components/ui/input.tsx
- tailwind.config.js
> design: 홈 화면의 필터 영역 반응형 1차 구현

- src/components/detail/Tab.tsx
- src/components/detail/TabSection.tsx
Reverts Wego-A-Journey-Together/Wego-FE#54
> Revert "fix: tab layout shift"

- public/data/trending.ts
- src/app/[lang]/detail/[id]/page.tsx
- src/components/detail/Tab.tsx
- src/components/detail/TabSection.tsx
- src/hooks/useScrollSection.ts
- 탭 UI 일부 수정 ( 클릭시 layout shift 문제)
- 탭 클릭시 scrollIntoView 효과 추가
- IntersectionObserver 활용한 ScrollSpy ( 스크롤시 탭 하이라이팅이 변화) 구현
- 탭 클릭으로 스크롤 이벤트 발생시 IntersectionObserver 비활성화 로직 작성 (탭 클릭시 하이라이팅이 바로 넘어감)
- eslint 에러처리
- hook 분리하였다가 다시 롤백
> feat: 탭 부분 ScrollSpy 구현

- .github/workflows/sync-fork.yml
- 메인에 merge가 완료되면 포크된 레포지토리에 자동으로 싱크하도록 추가하였습니다.
> chore: 포크된 레포지토리에 싱크하는 액션 추가

- .github/workflows/sync-fork.yml
- 현재 레포, 포크된 레포에서도 다 빌드 체크는 됐는데 push에서 통과하지 못해 수정해보고 있습니다..!
> fix: 포크된 레포에서 액션 오류 수정

- src/app/[lang]/layout.tsx
- src/app/[lang]/profile/[userId]/page.tsx
- src/components/Nav/Hamburger.tsx
- src/components/Nav/NavBar.tsx
- src/components/ThemeToggler/DarkModeToggler.tsx
- src/components/common/Tab.tsx
- src/components/detail/ScrollSpy.tsx
- src/components/detail/TabSection.tsx
- src/components/profile/DropDown.tsx
> feat: Profile  페이지 드롭다운, 탭 조건부 랜더링 구현

- src/app/[lang]/layout.tsx
- src/components/ThemeToggler/DarkModeToggler.tsx
- html 태그의 lang ='ko' 부분을 경로에 따라 동적으로 할당
- 쿠키가 없는 사용자에 대해 최초 접근시 시스템 컬러 적용
- Hydration warning 은 trancy 확장 프로그램 때문이었음 ( 코드 에서 기인한 경고가 아님 확인 )
https://github.com/user-attachments/assets/fecb9146-4926-417d-8ccd-00003f3f34a8
https://github.com/user-attachments/assets/b88a85cb-b1ee-4646-bcc2-75cea9ba6a04
> chore: multilingual darkmode

- src/app/[lang]/page.tsx
- chore : localhost8080 포트 -> process.env.로 수정하였습니다.
> hotfix: 로컬 호스트 8080 유지하여 배포 에러 발생

- src/app/[lang]/page.tsx
- src/app/[lang]/write/page.tsx
- src/components/Editor/PostSetupPanel.tsx
- src/components/home/filter/GroupThemeFilter.tsx
- src/components/profile/ConfirmMember.tsx
- src/components/profile/DropDown.tsx
- src/components/profile/GroupCreateByUser.tsx
- src/components/profile/MyComments.tsx
- src/components/ui/checkbox.tsx
> design: 글쓰기 페이지의 선호 정보 선택란 컴포넌트 제작

- src/app/globals.css
- src/components/Nav/NavBar.tsx
> fix: fixed 요소 레이아웃 쉬프트 해결

- next.config.ts
- src/components/Btn/Like.tsx
- src/components/common/RecruitPost.tsx
- src/components/detail/PostComment.tsx
- src/components/detail/PostReview.tsx
- src/components/home/InfiniteScroll.tsx
- src/lib/calculateDays.ts
- src/lib/convertAgeRange.ts
- src/lib/dateFormat.ts
- src/lib/index.ts
- src/types/HomePost.ts
- 홈페이지 무한 스크롤 영역 데이터 하드코딩 -> ajax 요청 방식으로 수정하였습니다.
- post 타입은 types/HomePost.ts 에 추가 했습니다. 
- *필드명이 약간 다릅니다. imageSrc -> thumbnailUrl , hashTags -> tags, age -> userAge 등
- [스웨거 주소](https://gateway.wego-travel.click/api-docs)
- s3 도메인 반영이 안되어서 수정 완료 했습니다. https://wego-travel.click/ko/write 에서 테스트 가능합니다. 
- 머지 후 스웨거 올리겠습니다 !
> refactor: 홈페이지 데이터 하드코딩 부분 수정

- src/app/[lang]/layout.tsx
- [lang] 의 layout.tsx 에서 유저 로그인 상태를 ssr로 받아오는 부분이 문제가 되었습니다. 
- 현재 BE 서버가 잠시 내려간 상태인데, 이 경우 Vercel timeout 발생하여 10초간 화면이 보이지 않고 504 에러페이지가 나옵니다.
- AbortController 등록해서 무응답시 홈페이지 랜더링 하도록 수정했습니다. ( 3초후 fetch 취소 )
> feat: 서버 무응답 방어코드 작성

- src/components/Btn/LogoutBtn.tsx
- src/components/Nav/AuthNav.tsx
- src/components/Nav/Hamburger.tsx
- src/components/Nav/NavBar.tsx
- 로그아웃 버튼 (현재 디자인 없습니다.) 추가 후 서버 연결
> chore: 로그아웃

- src/app/[lang]/page.tsx
- src/app/[lang]/write/page.tsx
- src/app/api/filter/route.ts
- src/components/home/FilterSelector.tsx
- src/components/home/filter/DateFilter.tsx
- src/components/home/filter/GroupSizeFilter.tsx
- src/components/home/filter/MobileFilterModal.tsx
- src/components/home/filter/RecruitingCheckbox.tsx
- src/components/home/filter/ScrollCalender.tsx
- src/redux/slices/filterSlice.ts
- 모집 중인 동행 체크박스를 필터링에 추가했습니다. (isGroupOpen)
- isClosing, inOpen이 모달 창 닫기 관련 내용이었는데 햇갈리는 여지가 있어 isModalOpen, isModalClosing으로 변경했습니다.
- 글 작성시 필터링 부분과 겹치는 부분의 키값을 맞췄습니다. 
- 날짜를 객체 안에 중첩으로 담았었는데 평탄화하고 UTC로 시간 변환했습니다.
- 사용자가 선택한 값을 쿼리파라미터로 담는 로직 추가했습니다.
- 검색 기능은 어떻게 할지 아직 미지순데요.. 일단 사용자가 검색 키워드를 자유롭게 넣으면 그 string 값을 글 데이터 속에 지도 정보와 비교를 서 일치하면 불러오는 형식이 되어야할까요?
> feat: 필터링 부분 쿼리파라미터로 전송

- q
- src/app/[lang]/layout.tsx
- src/app/[lang]/write/page.tsx
- src/app/api/filter/route.ts
- 로그인 상태관리를 위해 dev에서 항상 '김드릴' 유저로 로그인 되도록 수정
- api 경로 올바르게 조정
> chore: dev모드 로그인상태 유지, api라우트 수정

- src/components/profile/ConfirmMember.tsx
- src/components/profile/MyComments.tsx
- 마이페이지 내에서 본인이 본인의 페이지에 들어온 경우에 내 동행에 대한 신청 현황, 내가 작성한 글을 불러오는 api를 부착하였습니다.
- api가 요청해도 지금은 에러만 발생하고 있어 기존 모킹데이터가 일단 뜨도록 해놨습니다.
> feat: 마이페이지에서 참여 신청 및 확정 관리, 내가 쓴 댓글 보기 1차 구현

- src/components/profile/ConfirmMember.tsx
- src/components/profile/DropDown.tsx
- src/components/profile/GroupCreateByUser.tsx
- src/hooks/useSelectMyGathering.ts
- src/lib/checkClosed.ts
- src/lib/fetcher/fetchGatheringAppliers.ts
- src/lib/fetcher/fetchMySonGroup.ts
- src/lib/service/gatheringApi.ts
- 동행별로 유저 승인, 거절 기능 추가했습니다. 테스트후 업데이트 하겠습니다.
-
- 한솔님이 짜두신 로직 유지하고 부모 컴포넌트에서 postId만 넘기는 방식으로 전체 수정했습니다.
-
> Feat: 나의동행 -> 내 동행: 유저 승락 기능 구현

- src/components/profile/GroupCreateByUser.tsx
- src/lib/fetcher/fetchDeletePost.ts
- 수정하기, 숨기기 버튼에 api 연결했습니다.
- 글 수정, 삭제 잘 되는지 테스트 해보겟습니다.
-
-
-
> feat: 글 작성 , 글 삭제 api 연결 및 버튼 처리

- src/components/write/PostForm.tsx
> chore: rollback용 더미 커밋 (웹소켓 주소 상태 유지)

- src/components/common/RecruitPost.tsx
- src/components/profile/MyGroupPost.tsx
- src/components/profile/ReviewEditor.tsx
- src/components/profile/ReviewImageUploader.tsx
- src/hooks/fetch/useGetMyProfile.ts
- src/types/BEHomePost.ts
- 만들어주신 폼에서 api 연결후에 이미지 업로드 까지 구현해 두었습니다.
- img 필드는 없지만 <<IMAGE>> 이렇게 구분자 넣어서 s3 url 파싱하면 랜더링도 될 것 같습니다.
-
> feat: 소감 post 기능

- src/app/[lang]/detail/[id]/page.tsx
- src/components/Review/FetchMoreReviews.tsx
- src/components/detail/PostReview.tsx
- src/components/detail/ReviewRating.tsx
- src/components/detail/ScrollSpy.tsx
- src/components/detail/TabSection.tsx
- src/components/detail/UserProfile.tsx
- src/components/profile/ReviewEditor.tsx
- src/lib/fetcher/fetchReviews.ts
- 댓글 부분과 동일한 로직으로 작성했습니다. ( 답글 유무만 diff ) 
(<<이미지>>null 부분은 해결 완료 하였습니다. 텍스트만 있는 경우라고 생각해 주세요)
> feat: detail 소감 섹션 페이징 구현

- src/app/[lang]/detail/[id]/page.tsx
- src/components/MultiLingual/MultiLingualToggler.tsx
- src/components/Nav/SearchBar.tsx
- src/components/Review/FetchMoreReviews.tsx
- src/components/common/RecruitPost.tsx
- src/components/detail/KakaoMapViewer.tsx
- src/components/detail/PostContent.tsx
- src/components/detail/PostReview.tsx
- src/components/detail/UserProfile.tsx
- src/components/profile/MyComments.tsx
- src/components/profile/MyGroupPost.tsx
- src/components/write/KakaoKeywordSearch.tsx
- src/components/write/PostForm.tsx
- 디자이너분들 QA 참고해서 수정 가능한 부분은 수정했습니다 ( 채팅 관련 부분과 동행구함, 마감몇시간전 제외 )
> design: 디자이너 QA 반영
